remote_theme: thelehhman/texture

texture:
  title: Artem Vasilyev
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

social_links:
  github:  art-vasilyev
  linkedIn: in/art-vasilyev
